version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - ft_transcendence_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  ft_transcendence_postgres_data:
