version: '3.8'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/ssl:/etc/nginx/ssl"  # Ensure this path is correct
    depends_on:
      - frontend
    networks:
      - app_network

  backend:
    build: ./backend
    expose:
      - 8000
    depends_on:
      - frontend
    networks:
      - app_network

  frontend:
    build: ./frontend
    expose:
      - 5173
    networks:
      - app_network

networks:
  app_network:
    driver: bridge