version: '3.8'
services:
  backend:
    build: ./backend
    # expose:
    #   - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    
  frontend:
    build: ./frontend
    # ports:
    #   - "5173:5173"
    volumes:
      - ./frontend:/app
  
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
