# Generated by Django 4.2.17 on 2024-12-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.CharField(blank=True, default="I don't just play ping pong—I redefine it. Every serve, every smash, every point, I'm not just winning the game; I'm making history.", max_length=255, null=True),
        ),
    ]
