# Generated by Django 4.2.17 on 2025-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_client_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_2fa_validated',
            field=models.BooleanField(default=True),
        ),
    ]
