# Generated by Django 5.1.1 on 2024-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
