# Generated by Django 5.1.1 on 2024-11-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_client_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
