# Generated by Django 5.1.1 on 2024-11-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_client_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
