# Generated by Django 5.1.1 on 2024-09-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authentification',
            new_name='user',
        ),
    ]
