# Generated by Django 5.1.1 on 2024-09-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_rename_authentification_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Authentification',
        ),
    ]
